import { defineField, defineType } from 'sanity'

export const dealer = defineType({
  name: 'dealer',
  title: 'Dealer',
  type: 'document',
  groups: [
    { name: 'identity', title: 'Identity', default: true },
    { name: 'location', title: 'Location & Map' },
    { name: 'contact', title: 'Contact' },
    { name: 'hours', title: 'Hours' },
    { name: 'services', title: 'Services & Capabilities' },
    { name: 'territory', title: 'Territory' },
    { name: 'media', title: 'Media' },
    { name: 'internal', title: 'Internal' },
  ],
  fields: [
    defineField({
      name: 'dealerCode',
      title: 'Dealer Code',
      type: 'string',
      group: 'identity',
      validation: (rule) => rule.required().uppercase(),
      description: 'Unique Kubota dealer code (e.g., "KBT-TH-001")',
    }),
    defineField({
      name: 'name',
      title: 'Dealer Name',
      type: 'string',
      group: 'identity',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'legalName',
      title: 'Legal Company Name',
      type: 'string',
      group: 'identity',
      description: 'For contracts and invoicing',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          { title: 'Active', value: 'active' },
          { title: 'Inactive', value: 'inactive' },
          { title: 'Pending Approval', value: 'pending' },
          { title: 'Terminated', value: 'terminated' },
        ],
      },
      initialValue: 'active',
    }),
    defineField({
      name: 'tier',
      title: 'Dealer Tier',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          { title: 'Platinum', value: 'platinum' },
          { title: 'Gold', value: 'gold' },
          { title: 'Silver', value: 'silver' },
          { title: 'Bronze', value: 'bronze' },
          { title: 'Authorized Service Only', value: 'service-only' },
        ],
      },
      initialValue: 'bronze',
    }),
    defineField({
      name: 'addressLine1',
      title: 'Address Line 1',
      type: 'string',
      group: 'location',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'addressLine2',
      title: 'Address Line 2',
      type: 'string',
      group: 'location',
    }),
    defineField({
      name: 'city',
      title: 'City/District',
      type: 'string',
      group: 'location',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'stateProvince',
      title: 'State/Province',
      type: 'string',
      group: 'location',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'postalCode',
      title: 'Postal Code',
      type: 'string',
      group: 'location',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'country',
      title: 'Country',
      type: 'string',
      group: 'location',
      options: {
        list: ['TH', 'MY', 'MM', 'VN', 'ID', 'PH', 'SG', 'KH', 'LA'],
      },
      validation: (rule) => rule.required(),
      initialValue: 'TH',
    }),
    defineField({
      name: 'location',
      title: 'Map Location (Lat/Lng)',
      type: 'geopoint',
      group: 'location',
      validation: (rule) => rule.required(),
      description: 'Pin on map for dealer locator. Drag to adjust.',
    }),
    defineField({
      name: 'mapEmbedUrl',
      title: 'Google Maps Embed URL',
      type: 'url',
      group: 'location',
      description: 'Optional: custom embed for directions button',
    }),
    defineField({
      name: 'phone',
      title: 'Main Phone',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'phoneSecondary',
      title: 'Secondary Phone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'phoneParts',
      title: 'Parts Department Phone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'phoneService',
      title: 'Service Department Phone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'phoneSales',
      title: 'Sales Department Phone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'email',
      title: 'Main Email',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.required().email(),
    }),
    defineField({
      name: 'emailParts',
      title: 'Parts Email',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: 'emailService',
      title: 'Service Email',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: 'emailSales',
      title: 'Sales Email',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: 'website',
      title: 'Dealer Website',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'facebook',
      title: 'Facebook Page URL',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'lineId',
      title: 'LINE Official Account ID',
      type: 'string',
      group: 'contact',
      description: 'For Thailand market - LINE OA ID',
    }),
    defineField({
      name: 'mondayOpen',
      title: 'Monday Open',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'mondayClose',
      title: 'Monday Close',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'tuesdayOpen',
      title: 'Tuesday Open',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'tuesdayClose',
      title: 'Tuesday Close',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'wednesdayOpen',
      title: 'Wednesday Open',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'wednesdayClose',
      title: 'Wednesday Close',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'thursdayOpen',
      title: 'Thursday Open',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'thursdayClose',
      title: 'Thursday Close',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'fridayOpen',
      title: 'Friday Open',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'fridayClose',
      title: 'Friday Close',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'saturdayOpen',
      title: 'Saturday Open',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'saturdayClose',
      title: 'Saturday Close',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'sundayOpen',
      title: 'Sunday Open',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'sundayClose',
      title: 'Sunday Close',
      type: 'string',
      group: 'hours',
    }),
    defineField({
      name: 'holidayHours',
      title: 'Holiday Hours Note',
      type: 'text',
      group: 'hours',
      rows: 2,
    }),
    defineField({
      name: 'sellsNewEquipment',
      title: 'Sells New Equipment',
      type: 'boolean',
      group: 'services',
      initialValue: true,
    }),
    defineField({
      name: 'sellsUsedEquipment',
      title: 'Sells Used Equipment',
      type: 'boolean',
      group: 'services',
      initialValue: false,
    }),
    defineField({
      name: 'hasPartsDepartment',
      title: 'Has Parts Department',
      type: 'boolean',
      group: 'services',
      initialValue: true,
    }),
    defineField({
      name: 'hasServiceDepartment',
      title: 'Has Service Department',
      type: 'boolean',
      group: 'services',
      initialValue: true,
    }),
    defineField({
      name: 'hasRentalFleet',
      title: 'Has Rental Fleet',
      type: 'boolean',
      group: 'services',
      initialValue: false,
    }),
    defineField({
      name: 'offersFinancing',
      title: 'Offers Financing',
      type: 'boolean',
      group: 'services',
      initialValue: true,
    }),
    defineField({
      name: 'offersWarrantyService',
      title: 'Authorized Warranty Service',
      type: 'boolean',
      group: 'services',
      initialValue: true,
    }),
    defineField({
      name: 'certifiedTechnicians',
      title: 'Number of Certified Technicians',
      type: 'number',
      group: 'services',
      initialValue: 0,
    }),
    defineField({
      name: 'serviceBays',
      title: 'Number of Service Bays',
      type: 'number',
      group: 'services',
      initialValue: 0,
    }),
    defineField({
      name: 'supportedCategories',
      title: 'Supported Product Categories',
      type: 'array',
      group: 'services',
      of: [{ type: 'string' }],
      options: {
        list: [
          'Compact Tractor', 'Utility Tractor', 'Mid-Size Tractor',
          'Excavator', 'Skid Steer', 'Track Loader', 'Wheel Loader',
          'UTV/RTV', 'Mower', 'Implement',
        ],
        layout: 'checkbox',
      },
    }),
    defineField({
      name: 'territory',
      title: 'Sales Territory',
      type: 'array',
      group: 'territory',
      of: [{ type: 'string' }],
      options: {
        list: ['Bangkok', 'Central', 'North', 'Northeast', 'East', 'West', 'South'],
        layout: 'checkbox',
      },
      description: 'Provinces/regions this dealer covers',
    }),
    defineField({
      name: 'exclusiveTerritory',
      title: 'Exclusive Territory',
      type: 'boolean',
      group: 'territory',
      initialValue: false,
    }),
    defineField({
      name: 'logo',
      title: 'Dealer Logo',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
    }),
    defineField({
      name: 'showroomImages',
      title: 'Showroom/Facility Images',
      type: 'array',
      group: 'media',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', type: 'string', title: 'Alt Text' },
            { name: 'caption', type: 'string', title: 'Caption' },
          ],
        },
      ],
    }),
    defineField({
      name: 'franchiseAgreementStart',
      title: 'Franchise Agreement Start Date',
      type: 'date',
      group: 'internal',
    }),
    defineField({
      name: 'franchiseAgreementEnd',
      title: 'Franchise Agreement End Date',
      type: 'date',
      group: 'internal',
    }),
    defineField({
      name: 'accountManager',
      title: 'Kubota Account Manager',
      type: 'reference',
      group: 'internal',
      to: [{ type: 'kubotaStaff' }],
    }),
    defineField({
      name: 'crmId',
      title: 'CRM ID (HubSpot/Salesforce)',
      type: 'string',
      group: 'internal',
    }),
    defineField({
      name: 'erpCode',
      title: 'ERP/SAP Code',
      type: 'string',
      group: 'internal',
    }),
    defineField({
      name: 'notes',
      title: 'Internal Notes',
      type: 'text',
      group: 'internal',
      rows: 3,
    }),
  ],
  preview: {
    select: {
      name: 'name',
      dealerCode: 'dealerCode',
      city: 'city',
      country: 'country',
      status: 'status',
      tier: 'tier',
      media: 'logo',
    },
    prepare({ name, dealerCode, city, country, status, tier, media }) {
      return {
        title: `${name} (${dealerCode})`,
        subtitle: `${city}, ${country} • ${tier} • ${status}`,
        media,
      }
    },
  },
})

export const kubotaStaff = defineType({
  name: 'kubotaStaff',
  title: 'Kubota Staff (Account Managers)',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      validation: (rule) => rule.required().email(),
    }),
    defineField({
      name: 'phone',
      title: 'Phone',
      type: 'string',
    }),
    defineField({
      name: 'region',
      title: 'Region',
      type: 'string',
      options: { list: ['Thailand', 'Myanmar', 'Vietnam', 'Indonesia', 'Malaysia', 'Regional'] },
    }),
    defineField({
      name: 'role',
      title: 'Role',
      type: 'string',
      options: { list: ['Area Manager', 'Territory Manager', 'Sales Support', 'Technical Support'] },
    }),
    defineField({
      name: 'isActive',
      title: 'Active',
      type: 'boolean',
      initialValue: true,
    }),
  ],
})