import { defineField, defineType } from 'sanity'

export const manual = defineType({
  name: 'manual',
  title: 'Manual / Document',
  type: 'document',
  groups: [
    { name: 'core', title: 'Core Info', default: true },
    { name: 'file', title: 'File & Version' },
    { name: 'applicability', title: 'Applicability' },
    { name: 'access', title: 'Access Control' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'core',
      validation: (rule) => rule.required().max(150),
      description: 'e.g., "M7060 Operator\'s Manual", "L3301 Parts Catalog"',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'core',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'type',
      title: 'Document Type',
      type: 'string',
      group: 'core',
      options: {
        list: [
          { title: 'Operator\'s Manual', value: 'operator' },
          { title: 'Service Manual', value: 'service' },
          { title: 'Parts Catalog', value: 'parts' },
          { title: 'Installation Guide', value: 'installation' },
          { title: 'Safety Manual', value: 'safety' },
          { title: 'Warranty Guide', value: 'warranty' },
          { title: 'Quick Reference Guide', value: 'quick-ref' },
          { title: 'Technical Bulletin', value: 'tech-bulletin' },
          { title: 'Software/Firmware Release Notes', value: 'release-notes' },
          { title: 'Other', value: 'other' },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      group: 'core',
      rows: 3,
      description: 'Brief summary shown in library listings',
    }),
    defineField({
      name: 'language',
      title: 'Language',
      type: 'string',
      group: 'core',
      options: {
        list: [
          { title: 'English', value: 'en' },
          { title: 'Thai', value: 'th' },
          { title: 'Burmese', value: 'my' },
          { title: 'Vietnamese', value: 'vi' },
          { title: 'Indonesian', value: 'id' },
          { title: 'Malay', value: 'ms' },
        ],
        layout: 'radio',
      },
      validation: (rule) => rule.required(),
      initialValue: 'en',
    }),
    defineField({
      name: 'file',
      title: 'PDF File',
      type: 'file',
      group: 'file',
      options: {
        accept: '.pdf',
        storeOriginalFilename: true,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'fileSize',
      title: 'File Size (bytes)',
      type: 'number',
      group: 'file',
      readOnly: true,
      hidden: true,
    }),
    defineField({
      name: 'pageCount',
      title: 'Page Count',
      type: 'number',
      group: 'file',
      validation: (rule) => rule.min(1).integer(),
    }),
    defineField({
      name: 'version',
      title: 'Version/Revision',
      type: 'string',
      group: 'file',
      validation: (rule) => rule.required(),
      description: 'e.g., "Rev. 2", "2024-01", "v1.3"',
    }),
    defineField({
      name: 'releaseDate',
      title: 'Release Date',
      type: 'date',
      group: 'file',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'supersedes',
      title: 'Supersedes (Previous Version)',
      type: 'reference',
      group: 'file',
      to: [{ type: 'manual' }],
      description: 'Link to the previous version this replaces',
    }),
    defineField({
      name: 'productSpecs',
      title: 'Applicable Models (ProductSpec)',
      type: 'array',
      group: 'applicability',
      of: [{ type: 'reference', to: [{ type: 'productSpec' }] }],
      validation: (rule) => rule.min(1),
      description: 'Select all models this manual applies to',
    }),
    defineField({
      name: 'seriesApplicability',
      title: 'Applicable Series',
      type: 'array',
      group: 'applicability',
      of: [{ type: 'reference', to: [{ type: 'productSeries' }] }],
      description: 'Or select entire series (overrides individual models)',
    }),
    defineField({
      name: 'serialNumberRange',
      title: 'Serial Number Range',
      type: 'object',
      group: 'applicability',
      fields: [
        { name: 'from', type: 'string', title: 'From Serial #' },
        { name: 'to', type: 'string', title: 'To Serial #' },
      ],
      description: 'For service bulletins covering specific serial ranges',
    }),
    defineField({
      name: 'engineModels',
      title: 'Applicable Engine Models',
      type: 'array',
      group: 'applicability',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'transmissionTypes',
      title: 'Applicable Transmission Types',
      type: 'array',
      group: 'applicability',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'accessLevel',
      title: 'Access Level',
      type: 'string',
      group: 'access',
      options: {
        list: [
          { title: 'Public (Anyone)', value: 'public' },
          { title: 'Dealer Portal (Logged-in Dealers)', value: 'dealer' },
          { title: 'Authorized Service Only', value: 'service' },
          { title: 'Internal (Kubota Staff Only)', value: 'internal' },
        ],
      },
      validation: (rule) => rule.required(),
      initialValue: 'public',
    }),
    defineField({
      name: 'allowedDealerTiers',
      title: 'Allowed Dealer Tiers',
      type: 'array',
      group: 'access',
      of: [{ type: 'string' }],
      options: {
        list: ['platinum', 'gold', 'silver', 'bronze', 'service-only'],
        layout: 'checkbox',
      },
      hidden: ({ document }) => document?.accessLevel !== 'dealer',
    }),
    defineField({
      name: 'allowedCountries',
      title: 'Allowed Countries',
      type: 'array',
      group: 'access',
      of: [{ type: 'string' }],
      options: {
        list: ['TH', 'MY', 'MM', 'VN', 'ID', 'PH', 'SG', 'KH', 'LA', 'GLOBAL'],
        layout: 'checkbox',
      },
      description: 'Restrict by country. GLOBAL = all countries.',
    }),
    defineField({
      name: 'requiresAcceptance',
      title: 'Requires Terms Acceptance',
      type: 'boolean',
      group: 'access',
      initialValue: false,
      description: 'Show terms modal before download',
    }),
    defineField({
      name: 'termsText',
      title: 'Terms & Conditions Text',
      type: 'text',
      group: 'access',
      rows: 4,
      hidden: ({ document }) => !document?.requiresAcceptance,
    }),
    defineField({
      name: 'watermarkText',
      title: 'Watermark Text (for downloaded PDF)',
      type: 'string',
      group: 'access',
      description: 'e.g., "CONFIDENTIAL - Kubota Dealer Use Only"',
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title',
      type: 'string',
      group: 'seo',
      validation: (rule) => rule.max(60),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'text',
      group: 'seo',
      rows: 2,
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: 'tags',
      title: 'Search Tags',
      type: 'array',
      group: 'seo',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'Keywords for internal search (not visible to public)',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'core',
      options: {
        list: [
          { title: 'Draft', value: 'draft' },
          { title: 'Published', value: 'published' },
          { title: 'Archived', value: 'archived' },
          { title: 'Superseded', value: 'superseded' },
        ],
      },
      initialValue: 'draft',
    }),
    defineField({
      name: 'publishDate',
      title: 'Publish Date',
      type: 'datetime',
      group: 'core',
    }),
    defineField({
      name: 'expiryDate',
      title: 'Expiry Date',
      type: 'datetime',
      group: 'core',
      description: 'Auto-archive after this date (e.g., old service bulletins)',
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured in Library',
      type: 'boolean',
      group: 'core',
      initialValue: false,
    }),
    defineField({
      name: 'downloadCount',
      title: 'Download Count',
      type: 'number',
      group: 'core',
      readOnly: true,
      initialValue: 0,
      hidden: true,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      type: 'type',
      language: 'language',
      version: 'version',
      status: 'status',
      accessLevel: 'accessLevel',
      models: 'productSpecs',
      media: 'file',
    },
    prepare({ title, type, language, version, status, accessLevel, models, media }) {
      const modelNames = models?.map((m: any) => m.modelCode).join(', ') || 'No models'
      return {
        title: `${title} [${type}]`,
        subtitle: `v${version} • ${language.toUpperCase()} • ${accessLevel} • ${status} • ${modelNames}`,
        media,
      }
    },
  },
})

export const manualCategory = defineType({
  name: 'manualCategory',
  title: 'Manual Category (for Library Navigation)',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'icon',
      title: 'Icon Name',
      type: 'string',
      description: 'Lucide/FontAwesome icon name (e.g., "book-open", "wrench", "shield")',
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      initialValue: 0,
    }),
    defineField({
      name: 'documentTypes',
      title: 'Document Types in This Category',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          'operator', 'service', 'parts', 'installation',
          'safety', 'warranty', 'quick-ref', 'tech-bulletin', 'release-notes',
        ],
        layout: 'checkbox',
      },
    }),
    defineField({
      name: 'isActive',
      title: 'Active',
      type: 'boolean',
      initialValue: true,
    }),
  ],
})