import { defineField, defineType } from 'sanity'

export const productSpec = defineType({
  name: 'productSpec',
  title: 'Product Specification (Global)',
  type: 'document',
  groups: [
    { name: 'identity', title: 'Identity', default: true },
    { name: 'engine', title: 'Engine & Performance' },
    { name: 'dimensions', title: 'Dimensions & Weight' },
    { name: 'hydraulics', title: 'Hydraulics & PTO' },
    { name: 'transmission', title: 'Transmission' },
    { name: 'features', title: 'Features & Options' },
    { name: 'media', title: 'Media' },
  ],
  fields: [
    defineField({
      name: 'modelCode',
      title: 'Model Code',
      type: 'string',
      group: 'identity',
      validation: (rule) => rule.required().uppercase(),
      description: 'Unique internal code (e.g., "M7060", "L3301")',
    }),
    defineField({
      name: 'series',
      title: 'Series',
      type: 'reference',
      group: 'identity',
      to: [{ type: 'productSeries' }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          { title: 'Compact Tractor', value: 'compact-tractor' },
          { title: 'Utility Tractor', value: 'utility-tractor' },
          { title: 'Mid-Size Tractor', value: 'mid-size-tractor' },
          { title: 'Excavator', value: 'excavator' },
          { title: 'Skid Steer', value: 'skid-steer' },
          { title: 'Track Loader', value: 'track-loader' },
          { title: 'Wheel Loader', value: 'wheel-loader' },
          { title: 'UTV/RTV', value: 'utv-rtv' },
          { title: 'Mower', value: 'mower' },
          { title: 'Implement', value: 'implement' },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'generation',
      title: 'Generation',
      type: 'number',
      group: 'identity',
      initialValue: 1,
      validation: (rule) => rule.required().min(1).integer(),
    }),
    defineField({
      name: 'engineModel',
      title: 'Engine Model',
      type: 'string',
      group: 'engine',
    }),
    defineField({
      name: 'engineType',
      title: 'Engine Type',
      type: 'string',
      group: 'engine',
      options: {
        list: [
          { title: 'Diesel', value: 'diesel' },
          { title: 'Gasoline', value: 'gasoline' },
          { title: 'Electric', value: 'electric' },
        ],
      },
    }),
    defineField({
      name: 'grossHorsepower',
      title: 'Gross Horsepower (HP)',
      type: 'number',
      group: 'engine',
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: 'ptoHorsepower',
      title: 'PTO Horsepower (HP)',
      type: 'number',
      group: 'engine',
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: 'engineDisplacement',
      title: 'Displacement (L)',
      type: 'number',
      group: 'engine',
    }),
    defineField({
      name: 'cylinders',
      title: 'Cylinders',
      type: 'number',
      group: 'engine',
      options: { list: [2, 3, 4, 6] },
    }),
    defineField({
      name: 'aspiration',
      title: 'Aspiration',
      type: 'string',
      group: 'engine',
      options: {
        list: [
          { title: 'Natural', value: 'natural' },
          { title: 'Turbocharged', value: 'turbo' },
          { title: 'Turbo + Intercooled', value: 'turbo-intercooled' },
        ],
      },
    }),
    defineField({
      name: 'ratedRpm',
      title: 'Rated RPM',
      type: 'number',
      group: 'engine',
    }),
    defineField({
      name: 'fuelTankCapacity',
      title: 'Fuel Tank Capacity (L)',
      type: 'number',
      group: 'engine',
    }),
    defineField({
      name: 'defTankCapacity',
      title: 'DEF Tank Capacity (L)',
      type: 'number',
      group: 'engine',
    }),
    defineField({
      name: 'overallLength',
      title: 'Overall Length (mm)',
      type: 'number',
      group: 'dimensions',
    }),
    defineField({
      name: 'overallWidth',
      title: 'Overall Width (mm)',
      type: 'number',
      group: 'dimensions',
    }),
    defineField({
      name: 'overallHeight',
      title: 'Overall Height (mm)',
      type: 'number',
      group: 'dimensions',
      description: 'To top of ROPS/cab',
    }),
    defineField({
      name: 'wheelbase',
      title: 'Wheelbase (mm)',
      type: 'number',
      group: 'dimensions',
    }),
    defineField({
      name: 'groundClearance',
      title: 'Ground Clearance (mm)',
      type: 'number',
      group: 'dimensions',
    }),
    defineField({
      name: 'operatingWeight',
      title: 'Operating Weight (kg)',
      type: 'number',
      group: 'dimensions',
    }),
    defineField({
      name: 'frontTireSize',
      title: 'Front Tire Size',
      type: 'string',
      group: 'dimensions',
    }),
    defineField({
      name: 'rearTireSize',
      title: 'Rear Tire Size',
      type: 'string',
      group: 'dimensions',
    }),
    defineField({
      name: 'hydraulicPumpType',
      title: 'Hydraulic Pump Type',
      type: 'string',
      group: 'hydraulics',
      options: {
        list: [
          { title: 'Gear', value: 'gear' },
          { title: 'Piston', value: 'piston' },
        ],
      },
    }),
    defineField({
      name: 'hydraulicFlow',
      title: 'Total Hydraulic Flow (L/min)',
      type: 'number',
      group: 'hydraulics',
    }),
    defineField({
      name: 'rearRemoteValves',
      title: 'Rear Remote Valves',
      type: 'number',
      group: 'hydraulics',
      initialValue: 2,
    }),
    defineField({
      name: 'threePointCategory',
      title: '3-Point Hitch Category',
      type: 'string',
      group: 'hydraulics',
      options: {
        list: ['Cat 0', 'Cat 1', 'Cat 2', 'Cat 3', 'Cat 4'],
      },
    }),
    defineField({
      name: 'liftCapacity24in',
      title: 'Lift Capacity at 24" (kg)',
      type: 'number',
      group: 'hydraulics',
    }),
    defineField({
      name: 'ptoType',
      title: 'PTO Type',
      type: 'string',
      group: 'hydraulics',
      options: {
        list: [
          { title: 'Independent', value: 'independent' },
          { title: 'Live', value: 'live' },
          { title: 'Transmission-Driven', value: 'transmission' },
        ],
      },
    }),
    defineField({
      name: 'ptoSpeeds',
      title: 'PTO Speeds (RPM)',
      type: 'array',
      group: 'hydraulics',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'transmissionType',
      title: 'Transmission Type',
      type: 'string',
      group: 'transmission',
      options: {
        list: [
          { title: 'HST (Hydrostatic)', value: 'hst' },
          { title: 'Manual Shuttle', value: 'manual-shuttle' },
          { title: 'Power Shuttle', value: 'power-shuttle' },
          { title: 'CVT', value: 'cvt' },
          { title: 'Gear Drive', value: 'gear' },
        ],
      },
    }),
    defineField({
      name: 'numberOfRanges',
      title: 'Number of Ranges',
      type: 'number',
      group: 'transmission',
    }),
    defineField({
      name: 'numberOfGears',
      title: 'Number of Gears (F/R)',
      type: 'string',
      group: 'transmission',
      description: 'e.g., "12F/12R" or "3 Range HST"',
    }),
    defineField({
      name: 'maxForwardSpeed',
      title: 'Max Forward Speed (km/h)',
      type: 'number',
      group: 'transmission',
    }),
    defineField({
      name: 'differentialLock',
      title: 'Differential Lock',
      type: 'boolean',
      group: 'transmission',
      initialValue: true,
    }),
    defineField({
      name: 'fourWheelDrive',
      title: '4WD Type',
      type: 'string',
      group: 'transmission',
      options: {
        list: [
          { title: 'Mechanical', value: 'mechanical' },
          { title: 'Electro-Hydraulic', value: 'electro-hydraulic' },
          { title: 'Full-Time', value: 'full-time' },
        ],
      },
    }),
    defineField({
      name: 'standardFeatures',
      title: 'Standard Features',
      type: 'array',
      group: 'features',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'optionalFeatures',
      title: 'Optional Features',
      type: 'array',
      group: 'features',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'attachments',
      title: 'Compatible Attachments',
      type: 'array',
      group: 'features',
      of: [{ type: 'reference', to: [{ type: 'productSpec' }] }],
    }),
    defineField({
      name: 'mainImage',
      title: 'Main Image',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
      fields: [
        { name: 'alt', type: 'string', title: 'Alt Text' },
      ],
    }),
    defineField({
      name: 'gallery',
      title: 'Image Gallery',
      type: 'array',
      group: 'media',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [{ name: 'alt', type: 'string', title: 'Alt Text' }],
        },
      ],
    }),
    defineField({
      name: 'brochurePdf',
      title: 'Global Brochure PDF',
      type: 'file',
      group: 'media',
      options: { accept: '.pdf' },
    }),
    defineField({
      name: 'serviceManualPdf',
      title: 'Service Manual PDF',
      type: 'file',
      group: 'media',
      options: { accept: '.pdf' },
    }),
    defineField({
      name: 'partsManualPdf',
      title: 'Parts Manual PDF',
      type: 'file',
      group: 'media',
      options: { accept: '.pdf' },
    }),
    defineField({
      name: 'operatorManualPdf',
      title: 'Operator Manual PDF',
      type: 'file',
      group: 'media',
      options: { accept: '.pdf' },
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          { title: 'Active', value: 'active' },
          { title: 'Discontinued', value: 'discontinued' },
          { title: 'Upcoming', value: 'upcoming' },
        ],
      },
      initialValue: 'active',
    }),
    defineField({
      name: 'launchDate',
      title: 'Launch Date',
      type: 'date',
      group: 'identity',
    }),
    defineField({
      name: 'discontinuedDate',
      title: 'Discontinued Date',
      type: 'date',
      group: 'identity',
      hidden: ({ document }) => document?.status !== 'discontinued',
    }),
  ],
  preview: {
    select: {
      modelCode: 'modelCode',
      series: 'series.title',
      category: 'category',
      status: 'status',
      media: 'mainImage',
    },
    prepare({ modelCode, series, category, status, media }) {
      return {
        title: `${modelCode} ${series ? `(${series})` : ''}`,
        subtitle: `${category} • ${status}`,
        media,
      }
    },
  },
})

export const productSeries = defineType({
  name: 'productSeries',
  title: 'Product Series',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'image',
      title: 'Series Image',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      initialValue: 0,
    }),
  ],
})