import { defineField, defineType } from 'sanity'

const localeList = [
  { title: 'English (Global)', value: 'en' },
  { title: 'Thai', value: 'th' },
  { title: 'Burmese', value: 'my' },
  { title: 'Vietnamese', value: 'vi' },
  { title: 'Indonesian', value: 'id' },
  { title: 'Malay', value: 'ms' },
]

export const productMarketing = defineType({
  name: 'productMarketing',
  title: 'Product Marketing (Localized)',
  type: 'document',
  groups: [
    { name: 'core', title: 'Core Content', default: true },
    { name: 'pricing', title: 'Pricing & Promotions' },
    { name: 'seo', title: 'SEO' },
    { name: 'media', title: 'Localized Media' },
  ],
  fields: [
    defineField({
      name: 'productSpec',
      title: 'Product Specification (Global)',
      type: 'reference',
      group: 'core',
      to: [{ type: 'productSpec' }],
      validation: (rule) => rule.required(),
      description: 'Links to the global technical spec. One ProductSpec can have multiple ProductMarketing docs (one per locale).',
    }),
    defineField({
      name: 'locale',
      title: 'Locale',
      type: 'string',
      group: 'core',
      options: { list: localeList },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'market',
      title: 'Market/Country',
      type: 'string',
      group: 'core',
      options: {
        list: [
          { title: 'Global (Default)', value: 'global' },
          { title: 'Thailand', value: 'th' },
          { title: 'Myanmar', value: 'my' },
          { title: 'Vietnam', value: 'vn' },
          { title: 'Indonesia', value: 'id' },
          { title: 'Malaysia', value: 'my' },
        ],
      },
      validation: (rule) => rule.required(),
      initialValue: 'global',
    }),
    defineField({
      name: 'displayName',
      title: 'Display Name',
      type: 'string',
      group: 'core',
      validation: (rule) => rule.required().max(100),
      description: 'Customer-facing name (e.g., "Kubota M7060 Premium")',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      group: 'core',
      rows: 3,
      validation: (rule) => rule.max(300),
      description: 'Used in cards, listings, search results',
    }),
    defineField({
      name: 'longDescription',
      title: 'Long Description',
      type: 'array',
      group: 'core',
      of: [
        { type: 'block' },
        { type: 'image', options: { hotspot: true } },
      ],
      description: 'Full product page description with rich text',
    }),
    defineField({
      name: 'keySellingPoints',
      title: 'Key Selling Points',
      type: 'array',
      group: 'core',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      validation: (rule) => rule.max(6),
      description: 'Bullet points for product cards (max 6)',
    }),
    defineField({
      name: 'applications',
      title: 'Target Applications',
      type: 'array',
      group: 'core',
      of: [{ type: 'string' }],
      options: {
        list: [
          'Rice Farming', 'Field Crops', 'Orchards', 'Livestock', 'Landscaping',
          'Construction', 'Municipal', 'Snow Removal', 'Material Handling',
        ],
        layout: 'checkbox',
      },
    }),
    defineField({
      name: 'targetAudience',
      title: 'Target Audience',
      type: 'array',
      group: 'core',
      of: [{ type: 'string' }],
      options: {
        list: ['Smallholder Farmers', 'Commercial Farms', 'Contractors', 'Dealers', 'Government', 'Landscapers'],
        layout: 'checkbox',
      },
    }),
    defineField({
      name: 'msrp',
      title: 'MSRP (Manufacturer Suggested Retail Price)',
      type: 'number',
      group: 'pricing',
      description: 'Base price in local currency (before dealer discounts)',
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      group: 'pricing',
      options: {
        list: [
          { title: 'THB (฿)', value: 'THB' },
          { title: 'MMK (K)', value: 'MMK' },
          { title: 'VND (₫)', value: 'VND' },
          { title: 'IDR (Rp)', value: 'IDR' },
          { title: 'MYR (RM)', value: 'MYR' },
          { title: 'USD ($)', value: 'USD' },
        ],
      },
      validation: (rule) => rule.required(),
      initialValue: 'THB',
    }),
    defineField({
      name: 'priceIncludes',
      title: 'Price Includes',
      type: 'array',
      group: 'pricing',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'e.g., "ROPS", "Standard Tires", "Delivery to Dealer"',
    }),
    defineField({
      name: 'priceExcludes',
      title: 'Price Excludes',
      type: 'array',
      group: 'pricing',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'e.g., "Implements", "Dealer Prep", "Taxes", "Insurance"',
    }),
    defineField({
      name: 'financingOptions',
      title: 'Financing Options',
      type: 'array',
      group: 'pricing',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'name', type: 'string', title: 'Program Name' },
            { name: 'description', type: 'text', title: 'Description', rows: 2 },
            { name: 'apr', type: 'number', title: 'APR %' },
            { name: 'termMonths', type: 'number', title: 'Term (months)' },
            { name: 'downPaymentPercent', type: 'number', title: 'Down Payment %' },
            { name: 'validUntil', type: 'date', title: 'Valid Until' },
          ],
        },
      ],
    }),
    defineField({
      name: 'promotions',
      title: 'Active Promotions',
      type: 'array',
      group: 'pricing',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'title', type: 'string', title: 'Promotion Title' },
            { name: 'description', type: 'text', title: 'Description', rows: 2 },
            { name: 'discountType', type: 'string', title: 'Type', options: { list: ['Cash Back', 'Rate Reduction', 'Free Implement', 'Extended Warranty', 'Service Package'] } },
            { name: 'discountValue', type: 'number', title: 'Value' },
            { name: 'startDate', type: 'date', title: 'Start Date' },
            { name: 'endDate', type: 'date', title: 'End Date' },
            { name: 'termsConditions', type: 'text', title: 'Terms & Conditions', rows: 3 },
          ],
        },
      ],
    }),
    defineField({
      name: 'dealerIncentives',
      title: 'Dealer Incentives (Internal)',
      type: 'text',
      group: 'pricing',
      rows: 3,
      description: 'Visible only to logged-in dealers',
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title',
      type: 'string',
      group: 'seo',
      validation: (rule) => rule.max(60),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'text',
      group: 'seo',
      rows: 2,
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: 'metaKeywords',
      title: 'Meta Keywords',
      type: 'array',
      group: 'seo',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'ogImage',
      title: 'Open Graph Image',
      type: 'image',
      group: 'seo',
      options: { hotspot: true },
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical URL',
      type: 'url',
      group: 'seo',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image (Localized)',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt Text' }],
    }),
    defineField({
      name: 'lifestyleImages',
      title: 'Lifestyle/Application Images',
      type: 'array',
      group: 'media',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', type: 'string', title: 'Alt Text' },
            { name: 'caption', type: 'string', title: 'Caption' },
          ],
        },
      ],
    }),
    defineField({
      name: 'videoUrl',
      title: 'Product Video URL (YouTube/Vimeo)',
      type: 'url',
      group: 'media',
    }),
    defineField({
      name: 'brochurePdf',
      title: 'Localized Brochure PDF',
      type: 'file',
      group: 'media',
      options: { accept: '.pdf' },
      description: 'Overrides global brochure if provided',
    }),
    defineField({
      name: 'specSheetPdf',
      title: 'Localized Spec Sheet PDF',
      type: 'file',
      group: 'media',
      options: { accept: '.pdf' },
      description: 'Marketing override for auto-generated PDF',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'core',
      options: {
        list: [
          { title: 'Draft', value: 'draft' },
          { title: 'Published', value: 'published' },
          { title: 'Archived', value: 'archived' },
        ],
      },
      initialValue: 'draft',
    }),
    defineField({
      name: 'publishDate',
      title: 'Publish Date',
      type: 'datetime',
      group: 'core',
    }),
    defineField({
      name: 'expiryDate',
      title: 'Expiry Date',
      type: 'datetime',
      group: 'core',
      description: 'Auto-archive after this date (optional)',
    }),
  ],
  preview: {
    select: {
      displayName: 'displayName',
      locale: 'locale',
      market: 'market',
      status: 'status',
      spec: 'productSpec.modelCode',
      media: 'heroImage',
    },
    prepare({ displayName, locale, market, status, spec, media }) {
      return {
        title: `${displayName} [${locale.toUpperCase()}]`,
        subtitle: `${spec} • ${market} • ${status}`,
        media,
      }
    },
  },
})

export const locale = defineType({
  name: 'locale',
  title: 'Supported Locale',
  type: 'document',
  fields: [
    defineField({
      name: 'code',
      title: 'Locale Code',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'name',
      title: 'Display Name',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'country',
      title: 'Country Code (ISO 3166-1 alpha-2)',
      type: 'string',
      validation: (rule) => rule.required().length(2),
    }),
    defineField({
      name: 'currency',
      title: 'Default Currency',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'dateFormat',
      title: 'Date Format',
      type: 'string',
      initialValue: 'DD/MM/YYYY',
    }),
    defineField({
      name: 'numberFormat',
      title: 'Number Format Locale',
      type: 'string',
      initialValue: 'th-TH',
    }),
    defineField({
      name: 'isRtl',
      title: 'Right-to-Left',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'isActive',
      title: 'Active',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      initialValue: 0,
    }),
  ],
})